
CREATE TABLE [dbo].[USER]
(
[USERNAME] NVARCHAR(50), 
[PASSWORD] VARCHAR(20) ,
);
--观察“一起帮”的注册和发布求助功能，试着建立表User：包含UserName（用户名），Password（密码）…… 
--为User表添加一列：邀请人（InvitedBy），类型为INT 
--将InvitedBy类型修改为NVARCHAR(10) 
--删除列InvitedBy
ALTER TABLE [USER]
ALTER COLUMN InvitedBy NVARCHAR(10);

ALTER TABLE [USER]
DROP COLUMN InvitedBy;

add invitedby int
GO

 SELECT * FROM [USER];

 INSERT [USER]([USERNAME] ) VALUES(N'17bang计算'); 

 INSERT [USER]([USERNAME] ,[PASSWORD]) VALUES(N'',2354); 

 INSERT [USER]([USERNAME] ,[PASSWORD] ) VALUES(N'小李',''); 

 INSERT [USER]([USERNAME] ,[PASSWORD]) VALUES(N'管理员',1562); 

 DROP TABLE [USER] ;

-- 查找没有录入密码的用户 
SELECT * FROM [USER] WHERE PASSWORD IS NULL OR PASSWORD = '';

SELECT [USERNAME] FROM [USER]  WHERE  PASSWORD IS  NULL  OR   PASSWORD = '' ; 
--删除用户名（UserName）中包含“管理员”或者“17bang”字样的用户

BEGIN TRAN 
DELETE [USER] WHERE  [USERNAME]  LIKE  N'%管理员%' OR [USERNAME] LIKE N'%17bang%'; 

ROLLBACK;

 SELECT * FROM [USER];

-- 添加Id列，让Id成为主键 
--添加约束，让UserName不能重复

ALTER TABLE [USER]
 ADD [ID] INT ;

 UPDATE [USER] SET ID = 4 WHERE  [USERNAME] = N'管理员';
 UPDATE [USER] SET ID = 3 WHERE  [USERNAME] = N'小李';
 UPDATE [USER] SET ID = 2 WHERE  [USERNAME] = N'';
 UPDATE [USER] SET ID = 1 WHERE  [USERNAME] = N'17bang计算';

 ALTER TABLE [USER]
 ALTER COLUMN [ID] INT  NOT  NULL;

 ALTER TABLE [USER]
 ADD CONSTRAINT PK_ID  PRIMARY KEY([ID]);

 ALTER TABLE [USER]
 DROP  COLUMN [ID];

 ALTER  TABLE [USER]
 ADD CONSTRAINT UQ_USERNAME UNIQUE  ([USERNAME]);

--将User表中Id列修改为可存储GUID的类型，并存入若干条包含GUID值的数据 

--ALTER TABLE [USER]
-- --DROP CONSTRAINT PK_ID;

-- ADD [ID] VARCHAR(500);

--INSERT [USER]([ID])  VALUES(NEWID()) ;

-- SELECT * FROM [USER];

--UPDATE [USER]  SET [ID] = NEWID() WHERE [ID]  IS  NULL ;