
CREATE TABLE [dbo].MESSAGE
(
 [ID] int,
 [FROMUSER] NVARCHAR(500),
 [TOUSER]  NVARCHAR(500),
 [UrgentLevel]  INT ,
 [Kind] NVARCHAR (200),
 [HasRead] INT ,
 [IsDelete] BIT,
 [Content] NTEXT,
);
INSERT MESSAGE  VALUES(1,N'来自小天',N'到小明',1,N'圣兽',2,0,N'刘大师赛收到的恐惧');

INSERT MESSAGE  VALUES(2,N'来自小李',N'到小黄',1,N'神兽',3,1,N'刘大师赛收到的恐惧');

ALTER TABLE MESSAGE 
ADD CONSTRAINT UQ_FROMUSER UNIQUE ([FROMUSER]);
 --INDEX  SEEK
SELECT * FROM MESSAGE WHERE FROMUSER = N'来自小天';

CREATE UNIQUE CLUSTERED INDEX IX_MESSAGE_ID ON MESSAGE(ID); 

DROP INDEX MESSAGE.IX_MESSAGE_ID

ALTER TABLE MESSAGE
--ALTER COLUMN [ID] INT  NOT  NULL;
ADD CONSTRAINT PK_ID PRIMARY KEY([ID] );

SELECT ID,TOUSER  FROM MESSAGE WHERE TOUSER = N'到小黄' ;

SELECT * FROM MESSAGE 



SELECT * FROM TSCORE OT
WHERE SCORE =
(
SELECT MAX(SCORE) FROM TSCORE IT
WHERE IT.[NAME]=OT.[NAME]
);

CREATE TABLE [dbo].[USER]
(
[USERNAME] NVARCHAR(500), 
[PASSWORD] VARCHAR(200) ,
);


--观察“一起帮”的注册和发布求助功能，试着建立表User：包含UserName（用户名），Password（密码）…… 
--为User表添加一列：邀请人（InvitedBy），类型为INT 
--将InvitedBy类型修改为NVARCHAR(10) 
--删除列InvitedBy
ALTER TABLE [USER]
ALTER COLUMN InvitedBy NVARCHAR(10);

ALTER TABLE [USER]
DROP COLUMN InvitedBy;

--ADD InvitedBy INT;

 SELECT * FROM [USER];

 
 INSERT [USER]([USERNAME] ,[PASSWORD]) VALUES(N'小明',1234); 

 INSERT [USER]([USERNAME] ) VALUES(N''); 

 INSERT [USER]([USERNAME] ,[PASSWORD] ) VALUES(N'小李',''); 

 INSERT [USER]([USERNAME] ) VALUES(N'管理员'); 

 INSERT [USER]([USERNAME] ,[PASSWORD]  ) VALUES(N'17bang',''); 

 INSERT [USER]([USERNAME] ,[PASSWORD] ) VALUES(N'管理员2',5678); 

-- 查找没有录入密码的用户 
--删除用户名（UserName）中包含“管理员”或者“17bang”字样的用户
SELECT [USERNAME] FROM [USER]  WHERE  PASSWORD IS  NULL  OR   PASSWORD = '' ; 

BEGIN TRAN 
DELETE [USER] WHERE  [USERNAME]  LIKE  N'%管理员%' OR [USERNAME] LIKE N'%17bang%'; 

ROLLBACK;

 SELECT * FROM [USER];

-- 添加Id列，让Id成为主键 
--添加约束，让UserName不能重复

ALTER TABLE [USER]
 ADD [ID] INT IDENTITY(1,1);

 ALTER TABLE [USER]
 ADD CONSTRAINT PK_ID  PRIMARY KEY([ID]);

 ALTER TABLE [USER]
 DROP  COLUMN [ID];

 DROP CONSTRAINT PK_ID;

 ALTER  TABLE [USER]
 ADD CONSTRAINT UQ_USERNAME UNIQUE  ([USERNAME]);


  --自动编号：NEWID()/IDENTITY 
 --给User表中添加一个GUID的Id列，并存入若干条数据 

 ALTER TABLE [USER]
 --DROP CONSTRAINT PK_ID;

 ADD [ID] VARCHAR(500);

INSERT [USER]([ID])  VALUES(NEWID()) ;

 SELECT * FROM [USER];

UPDATE [USER]  SET [ID] = NEWID() WHERE [ID]  IS  NULL ;

